<a href="https://colab.research.google.com/github/MAINKS/MACHINE-LEARNING/blob/main/data_1preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

In [ ]:
#Librarys are the symobol of modules containing functions and classes used to perform operations and actions. ex scikit learn contains all Ml required classes that we can use to create object of.

#Numpy - will allow us to work with arrays as Ml model requires array as input.

#Matplotlib - to plot graphs and charts , .pyplot is a module

#Pandas - allow us to import datasets & create matrix of features & dependent vector variable.

#Data slicing is done [1:9,8:10]
#Scikit learn is the library highly used in ml & have a module "model selection"used for Data preprocessing.

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#!pip install scikit-learn



## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Take care of missing data

In [ ]:
#Using average of all salarys , you can get the missing values in the columns.

#Scikit learn is library used to do this task. Class "simpleimputer" will be used.

#Imputer is created object of class "simpleimputer"

#Providing only numeric values(1st & 2nd col) to imputer using fit keyword.

#All rows and only columns with numeric data from X Matrix containing independent variables.
#Transform is used to update the values in the matrix.

from sklearn.impute import SimpleImputer  #importing simpleimputer from scikit library
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')  # creating object of class simpleimputer indicating task to perform & method
imputer.fit(X[:,1:3])   # accessing missing values from matrix
X[:,1:3]=imputer.transform(X[:,1:3])  # Updating missing values
print(X)



[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
# Converting categorical data into numerical data ,Country column containing (germany,france,spain) will be converted to numerical data.
# Germany france spain will be categorized individually
# Dependent variable (purchase) will be (Yes-1 , No - 0).
# One columntransfer class of compose module from scikit-learn library is used.
# Second class Onehotencoding from preprocessing module of scikit library is used to achieve this conversion.
# from sklearn.compose import ColumnTransformer
#      library  module        class name

# a new object (ct) of columntransformer class is created
#Matrix x is then transformed and fitted , stored in object ct as an array.

# MOST IMPORTANT:
#ColumnTransformer with Onehotencoder will be applied when column has variables as (germany,france,spain)
#LabelEncoder will be applied when column has variables as (Yes,No)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])] , remainder='passthrough')
#Object   class       details        encoder    encoding class  columns to transform.    remainder req to mention
X = np.array(ct.fit_transform(X))    #O/p saved in array , so array conversion is required
print(X)


#O/p - 10100 france 01001 spain 01010 germany are encoded in in binary.


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


#Encoding Dependent Variable

In [ ]:
#Importing class labelencoder from preprocessing module of sklearn library
#create an object name le for class label encoder
#applying fit & transform on Matrix y using object le created from labelencoder class to encode it to numerical value

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y)
y=le.transform(y)
       #or
y=LabelEncoder().fit_transform(y) #for ease
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the dataset into the Training set and Test set

In [ ]:
#IMP #Feature scaling is always applied after splitting data into training & test dataset as if
#done before , variation in the dataset will be observed due to mean standardisation that is
#not required in the test dataset used for model training - To prevent information leakage - as test set is supposed to be something new.

#Module "Model selection" with a defined class "Train_test_split" is used for spliiting dataset.
#4 matrices two for train & two for test dataset with each of dependent & independent variable.

from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=1)

# X & y matrices of train/test data  class name  Input as complete matrix X & y  data split size = 80/20  randomly splitting

print(X_train)
print("")
print(X_test)
print("")
print(y_train)
print("")
print(y_test)


[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]

[0 1 0 0 1 1 0 1]

[0 1]


## Feature Scaling

In [ ]:
# Feature scaling allows us to put all our data features on the same scale.
#To avoid some features dominating other features. To have all th value of features in the same range.
#Standardisation & normalisation
#Normalisation is preferred when we have normal features in most of the distrubiution
#Standardisation works in majorly all the conditions and is more preferred.   X_stand = X - mean(x)/StandardDeviation(X)
#Feature scaling is not done on test set , performed over train set & then transformed onto test set.

#StandardScaler class for standardisation from preprocessing module of scikitlearn library is imported.
#StandardScaler class will automatically calculate mean and steandard deviation of X matrix & standardise the features of matrix and scaling is done.


#Most Asked ques by DataScience Community : Do we have to apply feature scaling on dummy variables in a matrix of features
#Answer : No , as dummy variables are already in the same scale range as other variables.
#Only apply Standardisation feature scaling to your numerical values only - Age & salary , don't apply on Country as it's dummy variable. Slicing of columns will be done.
#On X_train & test matrix it is applied , not on y matrix containing categorical data.


from sklearn.preprocessing import StandardScaler
sc=StandardScaler()   #object created
X_train[: , 3:]=sc.fit_transform(X_train[: , 3:])
X_test[:,3:]=sc.transform(X_test[:,3:])  #same scale used on both test and train matrix of X(Numerical data)
#All Rows & 3rd col onwards.    fit will calc the mean & StDeviation & transform will put into formula & calculate.
print(X_train)
print("\n")
print(X_test)


#Scaling of features age & salary done b/w range -2 & 2.
#Will help optimise training of ML model.




[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
