#Project - Artificial Neural Network model based on Regression

### For a large dataset within a organisation working in Manufacturing field , using ANN implementation , predicting the Output - Electrical energy power as per the circumstances given under Pressure , Temperature & Humidity, Vaccum etc.

### Importing the libraries

In [34]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [35]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [36]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')   #To read excel files using pandas , pd.read_excel is used
X = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

### Splitting the dataset into the Training set and Test set

In [37]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(X,y , test_size=0.2 , random_state = 0)

print(X_train)
print('\n')
print(X_test)
print('\n')
print(y_train)
print('\n')
print(y_test)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


[473.93 467.87 431.97 ... 459.01 462.72 428.12]


[431.23 460.01 461.14 ... 473.26 438.   463.28]


## Part 2 - Building the ANN

### Initializing the ANN

In [38]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [39]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

### Adding the second hidden layer

In [40]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

### Adding the output layer

In [41]:
ann.add(tf.keras.layers.Dense(units=1))

#No activation function required for the regression as o/p is numerical,
#only for classification, sigmoid (2 categories) or softmax(3 categories) activation fn it is required as we Obtain categorical data of larger scope

## Part 3 - Training the ANN

### Compiling the ANN

In [42]:
ann.compile(optimizer ='adam' , loss = 'mean_squared_error' , )

#mean_squared_error is loss fxn while implementing ANN in Regression , binary_crossentropy for classification

### Training the ANN model on the Training set

In [44]:
ann.fit(X_train , y_train , batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 2ms/step - loss: 26.4263
Epoch 2/100
240/240 [==============================] - 1s 2ms/step - loss: 27.2117
Epoch 3/100
240/240 [==============================] - 1s 2ms/step - loss: 26.8557
Epoch 4/100
240/240 [==============================] - 1s 2ms/step - loss: 26.7661
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 26.7633
Epoch 6/100
240/240 [==============================] - 1s 2ms/step - loss: 26.4852
Epoch 7/100
240/240 [==============================] - 1s 2ms/step - loss: 26.7948
Epoch 8/100
240/240 [==============================] - 1s 4ms/step - loss: 26.9735
Epoch 9/100
240/240 [==============================] - 1s 4ms/step - loss: 26.2921
Epoch 10/100
240/240 [==============================] - 1s 4ms/step - loss: 27.2927
Epoch 11/100
240/240 [==============================] - 1s 4ms/step - loss: 26.5583
Epoch 12/100
240/240 [==============================] - 1s 2ms/step - loss: 26.7485
E

### Predicting the results of the Test set

In [50]:
y_pred = ann.predict(X_test)

np.set_printoptions(precision = 2)   #numpy sets decimal point precison after 2 decimals
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

print('\n')
print('Here we have our Predicted output')
print(y_pred)

#Our Artificial neural network predicted the values accurately , very close to real results
#In this way here prediction Of EP(Net hourly Electrical Energy Output) is predicted well by ANN for Manufacturing Company

60/60 [==============================] - 0s 1ms/step
[[431.22 431.23]
 [462.72 460.01]
 [466.06 461.14]
 ...
 [473.51 473.26]
 [439.83 438.  ]
 [459.19 463.28]]


Here we have our Predicted output
[[431.22]
 [462.72]
 [466.06]
 ...
 [473.51]
 [439.83]
 [459.19]]
